version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: lucaserq
      MYSQL_PASSWORD: lucas@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - library-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
      build: .
      container_name: library-app
      ports:
        - "8080:8080"
      depends_on:
        mysql:
          condition: service_healthy
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
      networks:
        - library-network

volumes:
  mysql_data:

networks:
  library-network: